### ISSUE TITLE
Can you please make this iOS 7 compatible?

### ISSUE THREAD

**Issue by pjebs** [pascalbros/PAPermissions#1]

**Comment by pascalbros** [comment]
Normally it should work with iOS 7, the problem here is with the blur, the class for the blur effect is not there in iOS 7.
Anyway I'll try to find a way.

Pascal

**Comment by pjebs** [comment]
I think another problem is the changes to Location Permissions.

**Comment by pascalbros** [comment]
Check the latest commit https://github.com/pascalbros/PAPermissions/commit/b597c220de97ebf465a4c157be6ffe729ccca867
Unfortunately I can't test it right now.

Let me know.

**Comment by pjebs** [comment]
I'll have a good look at it soon.
I believe `AVAudioSession.sharedInstance().requestRecordPermission` works for iOS7

**Comment by pjebs** [comment]
Also why did you hardcode: `prefs:root=NOTIFICATIONS_ID`.

It should be 

```
let settingsUrl = NSURL(string: UIApplicationOpenSettingsURLString)
UIApplication.sharedApplication().openURL(settingsUrl!)
```

**Comment by pjebs** [comment]
Did you base yours on: https://github.com/nickoneill/PermissionScope ?

**Comment by pascalbros** [comment]
No, I did it from scratch.

Anyway I hardcoded that string because on iOS 7 you cannot use UIApplicationOpenSettingsURLString
