### ISSUE TITLE
Cannot enable declined permissions.

### ISSUE THREAD

**Issue by evermeer** [pascalbros/PAPermissions#13]
When you have declined one of the permission Calendar, Motion, Photo or Notifications then you can't enable them anymore from the app. The other permissions will go to the settings screen like it should.

**Comment by pascalbros** [comment]
Hi @evermeer, please be more specific.
Which iOS version are you using?

**Comment by evermeer** [comment]
I was just running the demo app using XCode 8 on an iOS 10 device.
Then after clicking on the enable button and then actually declining the permissions for the above mentioned permissions nothing will happen when you click the enable button for the 2nd time. With the other permissions you will go to the settings screen (what you would expect)

**Comment by pascalbros** [comment]
Solved.
See https://github.com/pascalbros/PAPermissions/commit/41f1d6ad76bf2824ba9d05f51f157b4b6d83f2c7 or `pod update`
