### ISSUE TITLE
Properties of PIPermissionsTableViewCell are unnecessarily weak

### ISSUE THREAD

**Issue by chrismcs** [pascalbros/PAPermissions#21]
In `PAPermissionsTableViewCell`, you have the following properties declared as weak:

```
weak var iconImageView: UIImageView!
weak var titleLabel: UILabel!
weak var detailsLabel: UILabel!
	
weak var permission: PAPermissionsItem!
	
fileprivate weak var rightDetailsContainer: UIView!
fileprivate weak var enableButton: UIButton!
fileprivate weak var checkingIndicator: UIActivityIndicatorView!
```

There is no circular reference from any of those properties back to `PAPermissionsTableViewCell`, so those should be regular / strong references.  Otherwise, you run the risk of your instance of `PAPermissionsTableViewCell` outliving one of those items and since they are all declared as being implicitly-unwrapped optionals, you'll crash in that scenario.

**Comment by pascalbros** [comment]
Dunno, it seems fine to me.
See, all the vars are references of UI components, normally the cell will be reused over and over and that particular var (weak) will never be released.
It will be released only when the user dismisses the view and according to me it is the correct behavior.
Maybe I'm wrong, so help me to get it right. :]

Cheers, Pascal

**Comment by chrismcs** [comment]
You might be "getting away with it" in practice at the moment, but that doesn't make it a good idea :-)  There is absolutely no need to declare these as weak - so you are introducing an unnecessary risk of these properties being deallocated when you don't expect them to be...and there's absolutely no benefit whatsoever to introducing this risk.  Then to add to that danger, you are sidestepping Swift's built-in protection on optional properties by implicitly unwrapping them - so now if any of those properties are deallocated, it's not just that you hit an unexpected condition, it will just crash.

Proper memory management rules say that "Object A" ought to have a strong reference to "Object B" if it cares about Object B staying around.  In this situation - `PAPermissionsTableViewCell` cares very much about all those properties staying around....even if no one else is retaining them - the cell itself cares about them.  By declaring something as weak, you are implicitly saying "I'm totally fine if these objects get released and my instance of them turns to nil".  The only reason you would ever declare something as weak is if you need to avoid a circular retain (typically in a parent/child situation).  Specifically, you need to use weak in the situation where "Object A" holds a reference to "Object B" and "Object B" holds a reference to "Object A".  In this case, you'd make the child have a weak reference back to the parent AND you would definitely not want to declare the parent as being implicitly unwrapped - given that a weak references makes it "possible" for the reference to the parent to become nil at any point, you'd want to use Swift's handy unwrapping syntax everywhere you refer to the parent.

I would also argue that technically, you really don't want to implicitly unwrap all those variables (regardless of declaring them as weak or not).  Instead, you should make an init method that asks for all those properties.  This makes your code much safer for anyone else interacting with it...currently, you are promising `PAPermissionsTableViewCell` that those properties are always set 100% of the time by the thing that creates it - but the Swift way to enforce that promise is to handle that during init - at which point you no longer have to implicitly unwrap them (which puts you in unnecessary danger of a crash if something else creates a `PAPermissionsTableViewCell` and forgets to manually set every single property).

Hope that helps.

For more info on memory management and the use of weak properties, this might be helpful:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html
