### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [pascalbros/PAPermissions#22]
So, my app uses PAPermissions to get all the approvals. If I use PAPermission's notifications settings, the `didRegisterForRemoteNotificationsWithDeviceToken` in AppDelegate is not called. It is getting called with regular Push notification setup.

Is there any other way to call the `didRegisterForRemoteNotificationsWithDeviceToken` from PAPermissions after the user allow? Or am I missing something that need to be implemented?

Thanks for any help.

**Comment by pascalbros** [comment]
Dear @AnnieNinaJoyceV 

In iOS 8 you should not use the method `didRegisterForRemoteNotificationsWithDeviceToken`, instead implement this one in your app delegate:

```
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings;
```

[More on this method](https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623022-application)

Let me know.

Cheers, Pascal.

**Comment by AnnieNinaJoyceV** [comment]
@pascalbros Thank you for the quick response!

I tried the following, and this method is not getting triggered too.

func application(_ application: UIApplication, didRegister notificationSettings: UIUserNotificationSettings) {
        if notificationSettings.types != .none {
            application.registerForRemoteNotifications()
        }
    }

**Comment by pascalbros** [comment]
Can you please check the method `didFailToRegisterForRemoteNotificationsWithError` in your AppDelegate?

**Comment by AnnieNinaJoyceV** [comment]
Yes, it is not getting called either.

**Comment by computerManSA** [comment]
same issue here ..
how can we get device token ?
