### ISSUE TITLE
Not working with Xcode 10

### ISSUE THREAD

**Issue by uetcis** [pascalbros/PAPermissions#36]
As the title, PAPermissions can't be compiled.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/25654046/42364900-65e32812-812f-11e8-93a0-76bd6ea43a3d.png">

**Comment by spaquet** [comment]
Proposed a fix (check Pull Request https://github.com/pascalbros/PAPermissions/pull/39)

**Comment by erolando** [comment]
> Proposed a fix (check Pull Request #39)

works, thanks

**Comment by pascalbros** [comment]
0.9.11 is out!
