### ISSUE TITLE
Use of private APIs

### ISSUE THREAD

**Issue by engine-turning** [pascalbros/PAPermissions#38]
App will sometimes get rejected when using the PAPermissions library because of the use of `prefs:root=`

> Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

**Comment by spaquet** [comment]
confirmed as a major issue.

**Comment by pascalbros** [comment]
0.9.11 is out!
