### ISSUE TITLE
error: Segmentation fault: 11

### ISSUE THREAD

**Issue by AlexGZC** [pascalbros/PAPermissions#43]
Not working with xcode 12.

3.	While evaluating request SILGenWholeModuleRequest(SIL Generation for module AES__El__Salvador)
4.	While emitting SIL for 'setupUI()' (at /Users/willygonzalez/Documents/iOS Projects/AESApp/AESApp/Helpers/PAPermissions/Classes/PAPermissionsTableViewCell.swift:63:5)
5.	While silgen emitFunction SIL function "@$s17AES__El__Salvador26PAPermissionsTableViewCellC7setupUIyyF".
 for 'setupUI()' (at /Users/willygonzalez/Documents/iOS Projects/AESApp/AESApp/Helpers/PAPermissions/Classes/PAPermissionsTableViewCell.swift:63:5)

error: Segmentation fault: 11

**Comment by deezaster** [comment]
I have the same problem!

**Comment by pascalbros** [comment]
Ok guys. Thanks.
Let me work on this during the weekend.

Cheers, P

**Comment by AKLVLUPHK20** [comment]
I have the same problem. Is that fixed?

**Comment by pascalbros** [comment]
No guys, sorry. I'm surfing these days and I don't have my macbook with me.
Coming back on 13th October.

**Comment by pascalbros** [comment]
Done!
https://github.com/pascalbros/PAPermissions/releases/tag/0.9.50
Just `pod update PAPermissions` and you should be good to go, let me know so I can close this issue.

Cheers! 🤙

**Comment by AlexGZC** [comment]
I updated it friend, still having same issue

**Comment by AlexGZC** [comment]
Made a restart and clean pods now is working!!

**Comment by pascalbros** [comment]
Cool, closing! 🚀
