### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by loicgriffie** [pascalbros/PAPermissions#8]
To help usage of the library, cocoapods support may help

**Comment by pascalbros** [comment]
Almost done and pushed but I'm waiting for the release of the new cocoapods because there are some issues with swift 3

Let's wait.

**Comment by pascalbros** [comment]
Done.
You can install PAPermissions by adding `pod 'PAPermissions'` to your Podspec file.

Tested with pod 1.1.0.rc.2, it will work with the next release of cocoapods.
