### ISSUE TITLE
Camera Roll Access >iOS10

### ISSUE THREAD

**Issue by hslightnin** [pascalbros/PAPermissions#9]
To protect user privacy, an iOS app linked on or after iOS 10.0, and which accesses the user’s photo library, must statically declare the intent to do so. Include the NSPhotoLibraryUsageDescription key in your app’s Info.plist file and provide a purpose string for this key. If your app attempts to access the user’s photo library without a corresponding purpose string, your app exits.

**Comment by joeblau** [comment]
@hslightnin  - If you really want to live on the edge...

``` ruby
pod 'PAPermissions', :git => 'https://github.com/joeblau/PAPermissions.git', :branch => 'UpdatePhotoLibraryUsage'
```
